import Header from "@/components/header";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/toaster";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";
import AppProvider from "./(auth)/Approvider";
import "./globals.css";

const inter = Inter({
  subsets: ["vietnamese"]
  // ,
  // weight: ["100", "300"],
});

// const myFont = localFont({
//   src: [
//     {
//       path: './Roboto-Thin.ttf',
//       weight: "300",
//     },
//     {
//       path: './Roboto-Regular.ttf',
//       weight: "300",
//     }
//   ],
//   display: 'swap',
//   variable: '--font-roboto' // Correctly set the variable without parentheses or array notation
// })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const cookieStore = cookies()
  const sessionToken = cookieStore.get('sessionToken')
  console.log("Root", cookieStore.get('sessionToken'))
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className}`}>
        <Toaster />
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          <AppProvider initalSesstionToken={
            sessionToken?.value
          } >
            {children}
          </AppProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
